import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131317',
        'surface-bright': '#39393d',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1f',
        'surface-container': '#201f23',
        'surface-container-high': '#2a292e',
        'surface-container-highest': '#353438',
        'on-surface': '#e5e1e7',
        'on-surface-variant': '#c4c7c8',
        'inverse-surface': '#e5e1e7',
        'inverse-on-surface': '#313034',
        outline: '#8e9192',
        'outline-variant': '#444748',
        'surface-tint': '#c6c6c7',
        primary: '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'inverse-primary': '#5d5f5f',
        secondary: '#7bd0ff',
        'on-secondary': '#00354a',
        'secondary-container': '#00a6e0',
        'on-secondary-container': '#00374d',
        tertiary: '#ffffff',
        'on-tertiary': '#3c0091',
        'tertiary-container': '#e9ddff',
        'on-tertiary-container': '#7342dd',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#001e2c',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',
        background: '#131317',
        'on-background': '#e5e1e7',
        'surface-variant': '#353438',
        surface: '#131317',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'nav-height': '72px',
        'terminal-height': '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'grid-pattern': '18px',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'Inter', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'JetBrains Mono', 'monospace'],
        'display-hero': ['var(--font-geist-sans)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-geist-sans)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-geist-sans)', 'Inter', 'sans-serif'],
        'label-sm': ['var(--font-geist-sans)', 'Inter', 'sans-serif'],
        'mono-data': ['var(--font-geist-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '0.15em', fontWeight: '200' }],
        'display-hero-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '200' }],
        'headline-lg': ['24px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
        'mono-data': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        glitch: {
          '0%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 1px)' },
          '40%': { transform: 'translate(-2px, -1px)' },
          '60%': { transform: 'translate(2px, 1px)' },
          '80%': { transform: 'translate(2px, -1px)' },
          '100%': { transform: 'translate(0)' },
        },
        scan: {
          from: { top: '0%' },
          to: { top: '100%' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '0.02' },
          '50%': { opacity: '0.08' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'glitch-reveal': {
          '0%': { opacity: '0', transform: 'skewX(-2deg) translateX(-10px)', filter: 'brightness(3)' },
          '60%': { opacity: '0.7', transform: 'skewX(0.5deg) translateX(3px)', filter: 'brightness(1.2)' },
          '100%': { opacity: '1', transform: 'skewX(0) translateX(0)', filter: 'brightness(1)' },
        },
        breathe: {
          '0%, 100%': { opacity: '0.02' },
          '50%': { opacity: '0.06' },
        },
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        glitch: 'glitch 3s infinite linear alternate-reverse',
        scan: 'scan 4s linear infinite',
        'pulse-slow': 'pulse-slow 4s ease-in-out infinite',
        'fade-in': 'fade-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'glitch-reveal': 'glitch-reveal 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        breathe: 'breathe 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
